//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nfse.abrasf.org.br", ConfigurationName="WebService.nfse")]
    public interface nfse
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/CancelarNfse", ReplyAction="*")]
        WebService.CancelarNfseResponse CancelarNfse(WebService.CancelarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/CancelarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.CancelarNfseResponse> CancelarNfseAsync(WebService.CancelarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarLoteRps", ReplyAction="*")]
        WebService.ConsultarLoteRpsResponse ConsultarLoteRps(WebService.ConsultarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(WebService.ConsultarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfseServicoPrestado", ReplyAction="*")]
        WebService.ConsultarNfseServicoPrestadoResponse ConsultarNfseServicoPrestado(WebService.ConsultarNfseServicoPrestadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfseServicoPrestado", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.ConsultarNfseServicoPrestadoResponse> ConsultarNfseServicoPrestadoAsync(WebService.ConsultarNfseServicoPrestadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfseServicoTomado", ReplyAction="*")]
        WebService.ConsultarNfseServicoTomadoResponse ConsultarNfseServicoTomado(WebService.ConsultarNfseServicoTomadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfseServicoTomado", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.ConsultarNfseServicoTomadoResponse> ConsultarNfseServicoTomadoAsync(WebService.ConsultarNfseServicoTomadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfsePorFaixa", ReplyAction="*")]
        WebService.ConsultarNfsePorFaixaResponse ConsultarNfsePorFaixa(WebService.ConsultarNfsePorFaixaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfsePorFaixa", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.ConsultarNfsePorFaixaResponse> ConsultarNfsePorFaixaAsync(WebService.ConsultarNfsePorFaixaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfsePorRps", ReplyAction="*")]
        WebService.ConsultarNfsePorRpsResponse ConsultarNfsePorRps(WebService.ConsultarNfsePorRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/ConsultarNfsePorRps", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(WebService.ConsultarNfsePorRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/RecepcionarLoteRps", ReplyAction="*")]
        WebService.RecepcionarLoteRpsResponse RecepcionarLoteRps(WebService.RecepcionarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/RecepcionarLoteRps", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(WebService.RecepcionarLoteRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/GerarNfse", ReplyAction="*")]
        WebService.GerarNfseResponse GerarNfse(WebService.GerarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/GerarNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.GerarNfseResponse> GerarNfseAsync(WebService.GerarNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/SubstituirNfse", ReplyAction="*")]
        WebService.SubstituirNfseResponse SubstituirNfse(WebService.SubstituirNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/SubstituirNfse", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.SubstituirNfseResponse> SubstituirNfseAsync(WebService.SubstituirNfseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/RecepcionarLoteRpsSincrono", ReplyAction="*")]
        WebService.RecepcionarLoteRpsSincronoResponse RecepcionarLoteRpsSincrono(WebService.RecepcionarLoteRpsSincronoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nfse.abrasf.org.br/RecepcionarLoteRpsSincrono", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.RecepcionarLoteRpsSincronoResponse> RecepcionarLoteRpsSincronoAsync(WebService.RecepcionarLoteRpsSincronoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarNfseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarNfseRequest", Namespace="http://nfse.abrasf.org.br", Order=0)]
        public WebService.CancelarNfseRequestBody Body;
        
        public CancelarNfseRequest()
        {
        }
        
        public CancelarNfseRequest(WebService.CancelarNfseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CancelarNfseRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nfseCabecMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nfseDadosMsg;
        
        public CancelarNfseRequestBody()
        {
        }
        
        public CancelarNfseRequestBody(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarNfseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarNfseResponse", Namespace="http://nfse.abrasf.org.br", Order=0)]
        public WebService.CancelarNfseResponseBody Body;
        
        public CancelarNfseResponse()
        {
        }
        
        public CancelarNfseResponse(WebService.CancelarNfseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CancelarNfseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string outputXML;
        
        public CancelarNfseResponseBody()
        {
        }
        
        public CancelarNfseResponseBody(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarLoteRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarLoteRpsRequest", Namespace="http://nfse.abrasf.org.br", Order=0)]
        public WebService.ConsultarLoteRpsRequestBody Body;
        
        public ConsultarLoteRpsRequest()
        {
        }
        
        public ConsultarLoteRpsRequest(WebService.ConsultarLoteRpsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ConsultarLoteRpsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nfseCabecMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarLoteRpsRequestBody()
        {
        }
        
        public ConsultarLoteRpsRequestBody(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarLoteRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarLoteRpsResponse", Namespace="http://nfse.abrasf.org.br", Order=0)]
        public WebService.ConsultarLoteRpsResponseBody Body;
        
        public ConsultarLoteRpsResponse()
        {
        }
        
        public ConsultarLoteRpsResponse(WebService.ConsultarLoteRpsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ConsultarLoteRpsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string outputXML;
        
        public ConsultarLoteRpsResponseBody()
        {
        }
        
        public ConsultarLoteRpsResponseBody(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfseServicoPrestadoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarNfseServicoPrestadoRequest", Namespace="http://nfse.abrasf.org.br", Order=0)]
        public WebService.ConsultarNfseServicoPrestadoRequestBody Body;
        
        public ConsultarNfseServicoPrestadoRequest()
        {
        }
        
        public ConsultarNfseServicoPrestadoRequest(WebService.ConsultarNfseServicoPrestadoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ConsultarNfseServicoPrestadoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nfseCabecMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfseServicoPrestadoRequestBody()
        {
        }
        
        public ConsultarNfseServicoPrestadoRequestBody(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfseServicoPrestadoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarNfseServicoPrestadoResponse", Namespace="http://nfse.abrasf.org.br", Order=0)]
        public WebService.ConsultarNfseServicoPrestadoResponseBody Body;
        
        public ConsultarNfseServicoPrestadoResponse()
        {
        }
        
        public ConsultarNfseServicoPrestadoResponse(WebService.ConsultarNfseServicoPrestadoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ConsultarNfseServicoPrestadoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string outputXML;
        
        public ConsultarNfseServicoPrestadoResponseBody()
        {
        }
        
        public ConsultarNfseServicoPrestadoResponseBody(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfseServicoTomadoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarNfseServicoTomadoRequest", Namespace="http://nfse.abrasf.org.br", Order=0)]
        public WebService.ConsultarNfseServicoTomadoRequestBody Body;
        
        public ConsultarNfseServicoTomadoRequest()
        {
        }
        
        public ConsultarNfseServicoTomadoRequest(WebService.ConsultarNfseServicoTomadoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ConsultarNfseServicoTomadoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nfseCabecMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfseServicoTomadoRequestBody()
        {
        }
        
        public ConsultarNfseServicoTomadoRequestBody(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfseServicoTomadoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarNfseServicoTomadoResponse", Namespace="http://nfse.abrasf.org.br", Order=0)]
        public WebService.ConsultarNfseServicoTomadoResponseBody Body;
        
        public ConsultarNfseServicoTomadoResponse()
        {
        }
        
        public ConsultarNfseServicoTomadoResponse(WebService.ConsultarNfseServicoTomadoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ConsultarNfseServicoTomadoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string outputXML;
        
        public ConsultarNfseServicoTomadoResponseBody()
        {
        }
        
        public ConsultarNfseServicoTomadoResponseBody(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfsePorFaixaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarNfsePorFaixaRequest", Namespace="http://nfse.abrasf.org.br", Order=0)]
        public WebService.ConsultarNfsePorFaixaRequestBody Body;
        
        public ConsultarNfsePorFaixaRequest()
        {
        }
        
        public ConsultarNfsePorFaixaRequest(WebService.ConsultarNfsePorFaixaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ConsultarNfsePorFaixaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nfseCabecMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfsePorFaixaRequestBody()
        {
        }
        
        public ConsultarNfsePorFaixaRequestBody(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfsePorFaixaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarNfsePorFaixaResponse", Namespace="http://nfse.abrasf.org.br", Order=0)]
        public WebService.ConsultarNfsePorFaixaResponseBody Body;
        
        public ConsultarNfsePorFaixaResponse()
        {
        }
        
        public ConsultarNfsePorFaixaResponse(WebService.ConsultarNfsePorFaixaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ConsultarNfsePorFaixaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string outputXML;
        
        public ConsultarNfsePorFaixaResponseBody()
        {
        }
        
        public ConsultarNfsePorFaixaResponseBody(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfsePorRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarNfsePorRpsRequest", Namespace="http://nfse.abrasf.org.br", Order=0)]
        public WebService.ConsultarNfsePorRpsRequestBody Body;
        
        public ConsultarNfsePorRpsRequest()
        {
        }
        
        public ConsultarNfsePorRpsRequest(WebService.ConsultarNfsePorRpsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ConsultarNfsePorRpsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nfseCabecMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nfseDadosMsg;
        
        public ConsultarNfsePorRpsRequestBody()
        {
        }
        
        public ConsultarNfsePorRpsRequestBody(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarNfsePorRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarNfsePorRpsResponse", Namespace="http://nfse.abrasf.org.br", Order=0)]
        public WebService.ConsultarNfsePorRpsResponseBody Body;
        
        public ConsultarNfsePorRpsResponse()
        {
        }
        
        public ConsultarNfsePorRpsResponse(WebService.ConsultarNfsePorRpsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ConsultarNfsePorRpsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string outputXML;
        
        public ConsultarNfsePorRpsResponseBody()
        {
        }
        
        public ConsultarNfsePorRpsResponseBody(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecepcionarLoteRpsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecepcionarLoteRpsRequest", Namespace="http://nfse.abrasf.org.br", Order=0)]
        public WebService.RecepcionarLoteRpsRequestBody Body;
        
        public RecepcionarLoteRpsRequest()
        {
        }
        
        public RecepcionarLoteRpsRequest(WebService.RecepcionarLoteRpsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RecepcionarLoteRpsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nfseCabecMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nfseDadosMsg;
        
        public RecepcionarLoteRpsRequestBody()
        {
        }
        
        public RecepcionarLoteRpsRequestBody(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecepcionarLoteRpsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecepcionarLoteRpsResponse", Namespace="http://nfse.abrasf.org.br", Order=0)]
        public WebService.RecepcionarLoteRpsResponseBody Body;
        
        public RecepcionarLoteRpsResponse()
        {
        }
        
        public RecepcionarLoteRpsResponse(WebService.RecepcionarLoteRpsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RecepcionarLoteRpsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string outputXML;
        
        public RecepcionarLoteRpsResponseBody()
        {
        }
        
        public RecepcionarLoteRpsResponseBody(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GerarNfseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GerarNfseRequest", Namespace="http://nfse.abrasf.org.br", Order=0)]
        public WebService.GerarNfseRequestBody Body;
        
        public GerarNfseRequest()
        {
        }
        
        public GerarNfseRequest(WebService.GerarNfseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GerarNfseRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nfseCabecMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nfseDadosMsg;
        
        public GerarNfseRequestBody()
        {
        }
        
        public GerarNfseRequestBody(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GerarNfseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GerarNfseResponse", Namespace="http://nfse.abrasf.org.br", Order=0)]
        public WebService.GerarNfseResponseBody Body;
        
        public GerarNfseResponse()
        {
        }
        
        public GerarNfseResponse(WebService.GerarNfseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GerarNfseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string outputXML;
        
        public GerarNfseResponseBody()
        {
        }
        
        public GerarNfseResponseBody(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubstituirNfseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubstituirNfseRequest", Namespace="http://nfse.abrasf.org.br", Order=0)]
        public WebService.SubstituirNfseRequestBody Body;
        
        public SubstituirNfseRequest()
        {
        }
        
        public SubstituirNfseRequest(WebService.SubstituirNfseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SubstituirNfseRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nfseCabecMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nfseDadosMsg;
        
        public SubstituirNfseRequestBody()
        {
        }
        
        public SubstituirNfseRequestBody(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubstituirNfseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubstituirNfseResponse", Namespace="http://nfse.abrasf.org.br", Order=0)]
        public WebService.SubstituirNfseResponseBody Body;
        
        public SubstituirNfseResponse()
        {
        }
        
        public SubstituirNfseResponse(WebService.SubstituirNfseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SubstituirNfseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string outputXML;
        
        public SubstituirNfseResponseBody()
        {
        }
        
        public SubstituirNfseResponseBody(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecepcionarLoteRpsSincronoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecepcionarLoteRpsSincronoRequest", Namespace="http://nfse.abrasf.org.br", Order=0)]
        public WebService.RecepcionarLoteRpsSincronoRequestBody Body;
        
        public RecepcionarLoteRpsSincronoRequest()
        {
        }
        
        public RecepcionarLoteRpsSincronoRequest(WebService.RecepcionarLoteRpsSincronoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RecepcionarLoteRpsSincronoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nfseCabecMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nfseDadosMsg;
        
        public RecepcionarLoteRpsSincronoRequestBody()
        {
        }
        
        public RecepcionarLoteRpsSincronoRequestBody(string nfseCabecMsg, string nfseDadosMsg)
        {
            this.nfseCabecMsg = nfseCabecMsg;
            this.nfseDadosMsg = nfseDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecepcionarLoteRpsSincronoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecepcionarLoteRpsSincronoResponse", Namespace="http://nfse.abrasf.org.br", Order=0)]
        public WebService.RecepcionarLoteRpsSincronoResponseBody Body;
        
        public RecepcionarLoteRpsSincronoResponse()
        {
        }
        
        public RecepcionarLoteRpsSincronoResponse(WebService.RecepcionarLoteRpsSincronoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RecepcionarLoteRpsSincronoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string outputXML;
        
        public RecepcionarLoteRpsSincronoResponseBody()
        {
        }
        
        public RecepcionarLoteRpsSincronoResponseBody(string outputXML)
        {
            this.outputXML = outputXML;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface nfseChannel : WebService.nfse, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class nfseClient : System.ServiceModel.ClientBase<WebService.nfse>, WebService.nfse
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public nfseClient() : 
                base(nfseClient.GetDefaultBinding(), nfseClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.nfseSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public nfseClient(EndpointConfiguration endpointConfiguration) : 
                base(nfseClient.GetBindingForEndpoint(endpointConfiguration), nfseClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public nfseClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(nfseClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public nfseClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(nfseClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public nfseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public WebService.CancelarNfseResponse CancelarNfse(WebService.CancelarNfseRequest request)
        {
            return base.Channel.CancelarNfse(request);
        }
        
        public System.Threading.Tasks.Task<WebService.CancelarNfseResponse> CancelarNfseAsync(WebService.CancelarNfseRequest request)
        {
            return base.Channel.CancelarNfseAsync(request);
        }
        
        public WebService.ConsultarLoteRpsResponse ConsultarLoteRps(WebService.ConsultarLoteRpsRequest request)
        {
            return base.Channel.ConsultarLoteRps(request);
        }
        
        public System.Threading.Tasks.Task<WebService.ConsultarLoteRpsResponse> ConsultarLoteRpsAsync(WebService.ConsultarLoteRpsRequest request)
        {
            return base.Channel.ConsultarLoteRpsAsync(request);
        }
        
        public WebService.ConsultarNfseServicoPrestadoResponse ConsultarNfseServicoPrestado(WebService.ConsultarNfseServicoPrestadoRequest request)
        {
            return base.Channel.ConsultarNfseServicoPrestado(request);
        }
        
        public System.Threading.Tasks.Task<WebService.ConsultarNfseServicoPrestadoResponse> ConsultarNfseServicoPrestadoAsync(WebService.ConsultarNfseServicoPrestadoRequest request)
        {
            return base.Channel.ConsultarNfseServicoPrestadoAsync(request);
        }
        
        public WebService.ConsultarNfseServicoTomadoResponse ConsultarNfseServicoTomado(WebService.ConsultarNfseServicoTomadoRequest request)
        {
            return base.Channel.ConsultarNfseServicoTomado(request);
        }
        
        public System.Threading.Tasks.Task<WebService.ConsultarNfseServicoTomadoResponse> ConsultarNfseServicoTomadoAsync(WebService.ConsultarNfseServicoTomadoRequest request)
        {
            return base.Channel.ConsultarNfseServicoTomadoAsync(request);
        }
        
        public WebService.ConsultarNfsePorFaixaResponse ConsultarNfsePorFaixa(WebService.ConsultarNfsePorFaixaRequest request)
        {
            return base.Channel.ConsultarNfsePorFaixa(request);
        }
        
        public System.Threading.Tasks.Task<WebService.ConsultarNfsePorFaixaResponse> ConsultarNfsePorFaixaAsync(WebService.ConsultarNfsePorFaixaRequest request)
        {
            return base.Channel.ConsultarNfsePorFaixaAsync(request);
        }
        
        public WebService.ConsultarNfsePorRpsResponse ConsultarNfsePorRps(WebService.ConsultarNfsePorRpsRequest request)
        {
            return base.Channel.ConsultarNfsePorRps(request);
        }
        
        public System.Threading.Tasks.Task<WebService.ConsultarNfsePorRpsResponse> ConsultarNfsePorRpsAsync(WebService.ConsultarNfsePorRpsRequest request)
        {
            return base.Channel.ConsultarNfsePorRpsAsync(request);
        }
        
        public WebService.RecepcionarLoteRpsResponse RecepcionarLoteRps(WebService.RecepcionarLoteRpsRequest request)
        {
            return base.Channel.RecepcionarLoteRps(request);
        }
        
        public System.Threading.Tasks.Task<WebService.RecepcionarLoteRpsResponse> RecepcionarLoteRpsAsync(WebService.RecepcionarLoteRpsRequest request)
        {
            return base.Channel.RecepcionarLoteRpsAsync(request);
        }
        
        public WebService.GerarNfseResponse GerarNfse(WebService.GerarNfseRequest request)
        {
            return base.Channel.GerarNfse(request);
        }
        
        public System.Threading.Tasks.Task<WebService.GerarNfseResponse> GerarNfseAsync(WebService.GerarNfseRequest request)
        {
            return base.Channel.GerarNfseAsync(request);
        }
        
        public WebService.SubstituirNfseResponse SubstituirNfse(WebService.SubstituirNfseRequest request)
        {
            return base.Channel.SubstituirNfse(request);
        }
        
        public System.Threading.Tasks.Task<WebService.SubstituirNfseResponse> SubstituirNfseAsync(WebService.SubstituirNfseRequest request)
        {
            return base.Channel.SubstituirNfseAsync(request);
        }
        
        public WebService.RecepcionarLoteRpsSincronoResponse RecepcionarLoteRpsSincrono(WebService.RecepcionarLoteRpsSincronoRequest request)
        {
            return base.Channel.RecepcionarLoteRpsSincrono(request);
        }
        
        public System.Threading.Tasks.Task<WebService.RecepcionarLoteRpsSincronoResponse> RecepcionarLoteRpsSincronoAsync(WebService.RecepcionarLoteRpsSincronoRequest request)
        {
            return base.Channel.RecepcionarLoteRpsSincronoAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.nfseSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding(System.ServiceModel.BasicHttpSecurityMode.Transport);
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.nfseSOAP))
            {
                //return new System.ServiceModel.EndpointAddress("https://cidadaoonline.barretos.sp.gov.br/webservice/nfse?wsdl"); //Produção
                return new System.ServiceModel.EndpointAddress("https://barretos.prefeitura.rlz.com.br/webservice/nfse?wsdl"); //Homologação
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return nfseClient.GetBindingForEndpoint(EndpointConfiguration.nfseSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return nfseClient.GetEndpointAddress(EndpointConfiguration.nfseSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            nfseSOAP,
        }
    }
}
